### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by are** [leocavalcante/encrypt#183] opened 2020-12-08 14:34 UTC
Are there plans/resources to migrate to null safety soon?

Guide: https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by leocavalcante** [comment] 2020-12-08 15:17
I could work on that, but it has some dependencies that doesn't support it yet:
```
Computing null safety support...
Dependencies                Current    Upgradable  Resolvable  Latest
args                        ✗1.6.0     ✗1.6.0      ✗1.6.0      ✗1.6.0
asn1lib                     ✗0.8.1     ✗0.8.1      ✗0.8.1      ✗0.8.1
clock                       ✗1.0.1     ✗1.0.1      ✗1.0.1      ✗1.0.1
collection                  ✗1.14.13   ✗1.14.13    ✗1.14.13    ✗1.14.13
crypto                      ✗2.1.5     ✗2.1.5      ✗2.1.5      ✗2.1.5
pointycastle                ✗2.0.0     ✗2.0.0      ✗2.0.0      ✗2.0.0
```

**Comment by technolion** [comment] 2021-02-10 12:51
For all of the above dependencies null-safety versions exist now. Please work on Null-Safety for `encrypt` as well.

**Comment by are** [comment] 2021-02-18 19:47
@leocavalcante If the work on NNBD hasn't been started yet, I can pick it up and create a PR. Just let me know ASAP.

**Comment by leocavalcante** [comment] 2021-02-18 20:25
@are I haven't started it yet. Can I assign it to you?

**Comment by are** [comment] 2021-02-18 21:18
Yes! I will be happy to help.

**Comment by leocavalcante** [comment] 2021-02-18 21:28
Appreciated!!

**Comment by bsutton** [comment] 2021-02-24 21:49
@are without appearing to impatient do you have an eta on a release?

**Comment by bsutton** [comment] 2021-02-24 21:54
And today I can't reproduce the problem using the beta.

**Comment by are** [comment] 2021-02-24 22:23
I'll finish my part by the end of tomorrow. The rest is up to @leocavalcante.

**Comment by bsutton** [comment] 2021-02-24 23:45
Thats fantastic.

Thanks for putting the effort in :)

**Comment by leocavalcante** [comment] 2021-02-25 23:44
It is now available at https://pub.dev/packages/encrypt/versions/5.0.0-beta.1
Thank you very much @are !!

**Closed by leocavalcante** 2021-02-25 23:44 UTC
Labels: enhancement, good first issue
